{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-gradle-plugin",
    "version": "3.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-gradle-plugin-3.4.0.jar",
          "url": "spring-boot-gradle-plugin-3.4.0.jar",
          "size": 146078,
          "sha512": "b00185eb2396264e704f47c138a626ec7fbe2d1844b2c6006968135ac9d5124c698d877ed63846a6a21f1485e0fc653f0c0b8a664cd552bb265235f3410c9a1f",
          "sha256": "5d595fd9c88bbe21216ac4a806633dbf44b0367be1a9b2600b653d6db4de4074",
          "sha1": "71d1825d7eedccd5570fe00d855e0a254a10ecde",
          "md5": "025a2fe7e3116c70599b50f139fefd77"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-buildpack-platform",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-loader-tools",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.spring.gradle",
          "module": "dependency-management-plugin",
          "version": {
            "requires": "1.1.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.25.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-gradle-plugin-3.4.0.jar",
          "url": "spring-boot-gradle-plugin-3.4.0.jar",
          "size": 146078,
          "sha512": "b00185eb2396264e704f47c138a626ec7fbe2d1844b2c6006968135ac9d5124c698d877ed63846a6a21f1485e0fc653f0c0b8a664cd552bb265235f3410c9a1f",
          "sha256": "5d595fd9c88bbe21216ac4a806633dbf44b0367be1a9b2600b653d6db4de4074",
          "sha1": "71d1825d7eedccd5570fe00d855e0a254a10ecde",
          "md5": "025a2fe7e3116c70599b50f139fefd77"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-gradle-plugin-3.4.0-javadoc.jar",
          "url": "spring-boot-gradle-plugin-3.4.0-javadoc.jar",
          "size": 322902,
          "sha512": "ed5a96111092ed84ca9491866b5ad9ddbd80fad6aa7d95ae12a64b10d8d461cb322f5aa98b1fcf9e8d623814f93f8eebec44e07a41c3c4af631e0f71e06f2f0c",
          "sha256": "22883aef5c6ccc3531e0fd6dd1b7102bbe82af03520d0c30fdca188af7f1c135",
          "sha1": "5fe2d37c80ab30daface0e4a7bfdd119db00d75e",
          "md5": "1e63e82ac4f96a6a9b808f94aa0e83da"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-gradle-plugin-3.4.0-sources.jar",
          "url": "spring-boot-gradle-plugin-3.4.0-sources.jar",
          "size": 83386,
          "sha512": "4de09bdea9557909b3aa3bbc4461c65c7d7b5885b040f363a75d9b88105cba184bf8c0129b0a4c201b0f637cffbc6488ae5ed1957a10336d0285646f2fd00a94",
          "sha256": "73c199a9bf366ddf99bd376aeb6736294f78c5b576abdc997e6b829a87479ab6",
          "sha1": "3be6d7a9c718fcc2e889524e88c2472b1b5b5911",
          "md5": "f818b1443530ab1bd4f017d762a40071"
        }
      ]
    }
  ]
}
