{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-buildpack-platform",
    "version": "3.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-buildpack-platform-3.4.0.jar",
          "url": "spring-boot-buildpack-platform-3.4.0.jar",
          "size": 296696,
          "sha512": "1ccf43de790619bd007f84247e38b83ea32db50eb2ff2aae1500b1141fee02c40df60ff375e96feff79c090f350a050878c2d8cc0548394db0ef82e88312daf8",
          "sha256": "d55c2148b7d5f6311f7c8ae5a580da450f2f71b1aaf3e0b1e2007a3aaef95a52",
          "sha1": "278316547921c21f3a857ee7ab762a92f616c561",
          "md5": "ddc482293cdf664b7ee9faab03ec5aff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.13.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.25.0"
          }
        },
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5",
          "version": {
            "requires": "5.4.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.0"
          }
        },
        {
          "group": "org.tomlj",
          "module": "tomlj",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-buildpack-platform-3.4.0.jar",
          "url": "spring-boot-buildpack-platform-3.4.0.jar",
          "size": 296696,
          "sha512": "1ccf43de790619bd007f84247e38b83ea32db50eb2ff2aae1500b1141fee02c40df60ff375e96feff79c090f350a050878c2d8cc0548394db0ef82e88312daf8",
          "sha256": "d55c2148b7d5f6311f7c8ae5a580da450f2f71b1aaf3e0b1e2007a3aaef95a52",
          "sha1": "278316547921c21f3a857ee7ab762a92f616c561",
          "md5": "ddc482293cdf664b7ee9faab03ec5aff"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-buildpack-platform-3.4.0-javadoc.jar",
          "url": "spring-boot-buildpack-platform-3.4.0-javadoc.jar",
          "size": 426700,
          "sha512": "de3ad0c33893acc6fe4c5b82babb04059aa58874be1e00a8dd485ffa8993b18c4f0d831cd6b7a5c0b40e0dbeee183945983db510c31bbef971369dc562314983",
          "sha256": "4e2f09668fa0e0fcfe9106770cc3ab12e4a09a054190eb18787e901d92c82e51",
          "sha1": "20c7f8236e659595f9a0ccadff3d0f36a408723e",
          "md5": "ed44e089cb5bebee63b72edf0dd69753"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-buildpack-platform-3.4.0-sources.jar",
          "url": "spring-boot-buildpack-platform-3.4.0-sources.jar",
          "size": 180022,
          "sha512": "59d3416d7f63f1e1ddc16c50ce20b0ad5c4bdcd807debff6114c3a9d1a1a884739cf91e630ab1e8cf56ccc0150fc7bde792539fce0bffb41c5ae68204fda86c4",
          "sha256": "c1db8205f3bb8e22910311941f15f31b570cd4dce029968fc6168e53e6dbca4e",
          "sha1": "f074092aa6adc15fd401a7086cc600b28e38d8dd",
          "md5": "1967fade923638687e6496dcb0c35414"
        }
      ]
    }
  ]
}
