{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-core",
    "version": "6.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-jcl",
          "version": {
            "requires": "6.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-core-6.2.0.jar",
          "url": "spring-core-6.2.0.jar",
          "size": 1954386,
          "sha512": "64da3f13d991fe8858893257366a60fd570733a2e4deb626cd4756dc26ceb934b7d7c864d953637163b17babda16cadb47c80adcd37d75d1464d96de81ef525d",
          "sha256": "3b82629da38717dd616a70ec1055f9a8e208d58132071a6314a32159f8bce162",
          "sha1": "b0d65768b9f99204857dc9a5548443c04ba61c79",
          "md5": "a71ac83315b83206a514d47c134bc53c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-jcl",
          "version": {
            "requires": "6.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-core-6.2.0.jar",
          "url": "spring-core-6.2.0.jar",
          "size": 1954386,
          "sha512": "64da3f13d991fe8858893257366a60fd570733a2e4deb626cd4756dc26ceb934b7d7c864d953637163b17babda16cadb47c80adcd37d75d1464d96de81ef525d",
          "sha256": "3b82629da38717dd616a70ec1055f9a8e208d58132071a6314a32159f8bce162",
          "sha1": "b0d65768b9f99204857dc9a5548443c04ba61c79",
          "md5": "a71ac83315b83206a514d47c134bc53c"
        }
      ]
    }
  ]
}
