{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.module",
    "module": "jackson-module-parameter-names",
    "version": "2.18.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.18.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-module-parameter-names-2.18.1.jar",
          "url": "jackson-module-parameter-names-2.18.1.jar",
          "size": 9461,
          "sha512": "474cf36fc34165ec1a8ffdfe8264cd0cad0393b7e8782158088d5b6add691057c2d86bcd748704567c69ec9ff2c9514aa83d603960f427ba001e9eca33dcd62f",
          "sha256": "33b4439bbac79f492939b8465be3467d2fde53f881916057959b98eab83d5d57",
          "sha1": "b8493505315f47b3e8cd66b07e1c4768e46a9ba1",
          "md5": "c75089828833369976a94f0a086e6670"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.18.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-module-parameter-names-2.18.1.jar",
          "url": "jackson-module-parameter-names-2.18.1.jar",
          "size": 9461,
          "sha512": "474cf36fc34165ec1a8ffdfe8264cd0cad0393b7e8782158088d5b6add691057c2d86bcd748704567c69ec9ff2c9514aa83d603960f427ba001e9eca33dcd62f",
          "sha256": "33b4439bbac79f492939b8465be3467d2fde53f881916057959b98eab83d5d57",
          "sha1": "b8493505315f47b3e8cd66b07e1c4768e46a9ba1",
          "md5": "c75089828833369976a94f0a086e6670"
        }
      ]
    }
  ]
}
