{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-loader-tools",
    "version": "3.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.25.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-loader-tools-3.4.0.jar",
          "url": "spring-boot-loader-tools-3.4.0.jar",
          "size": 464219,
          "sha512": "e2b2a35b2fca7e0481059f9e4763c191198bdb039abb24b66a1a3c9b5db96b496de59de0d6513c37d3435595a089cf0019df1617cb33d3002bfa15614f7175e8",
          "sha256": "4ae7bc16e0acfebaa2899611c823874c66b29dac5460aebce01b3efc2d9829ac",
          "sha1": "bedfc3374cae20bb0b82e0a8d64f7cfdd0a25c17",
          "md5": "8867c466c7497858b49901a546795ff7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.25.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-loader-tools-3.4.0.jar",
          "url": "spring-boot-loader-tools-3.4.0.jar",
          "size": 464219,
          "sha512": "e2b2a35b2fca7e0481059f9e4763c191198bdb039abb24b66a1a3c9b5db96b496de59de0d6513c37d3435595a089cf0019df1617cb33d3002bfa15614f7175e8",
          "sha256": "4ae7bc16e0acfebaa2899611c823874c66b29dac5460aebce01b3efc2d9829ac",
          "sha1": "bedfc3374cae20bb0b82e0a8d64f7cfdd0a25c17",
          "md5": "8867c466c7497858b49901a546795ff7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-loader-tools-3.4.0-javadoc.jar",
          "url": "spring-boot-loader-tools-3.4.0-javadoc.jar",
          "size": 250227,
          "sha512": "ef1718412df332673a946d32ac27ff7f69100b6d0ed2ce5138088877f9d4ff8624ddc3abe0cd5138d125573f152b27844d44a79bcc45363c8f322f6023491016",
          "sha256": "b440b22d7cf13c48810a0059f2cd74ce5659515c0b657d998877136f17b12211",
          "sha1": "846c0134eacf4c373b237d0dba5fd5d45951c6ba",
          "md5": "a6f9dd4980097b878684ac07d13c3ef3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-loader-tools-3.4.0-sources.jar",
          "url": "spring-boot-loader-tools-3.4.0-sources.jar",
          "size": 75169,
          "sha512": "25a37ef4ab69a361118bc101f0b052c558d381449b294a258c490e311d19965a6564233de9894bca24879a8ed685d3d05f61f5405baa012404b49b11f58c3761",
          "sha256": "c378cd65115aa1fa8874e1bac3af8199c47b31d19d9bb8b116227487eb1b9dd2",
          "sha1": "6ced701a543a74f06666d2b9b8d6ee7b35417260",
          "md5": "561bb8a6017914d5dbba59abf46d3ba5"
        }
      ]
    }
  ]
}
