{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-jcl",
    "version": "6.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-jcl-6.2.0.jar",
          "url": "spring-jcl-6.2.0.jar",
          "size": 24534,
          "sha512": "a973976d29f6af462fbb34295a3bcb2b28f68a2051681f14cf58a8f02ec45955dc6622c3567baf676790c072e34b7b859ee843576b6ec2f4c32b08eb986aed89",
          "sha256": "2b59288f030ce77a89ec88aa426f32eb9a309056f3646dd5157f9f31f0204fd7",
          "sha1": "2b8e7bb1e751bf585e7db6de1d375c599e0c8cf5",
          "md5": "32d57c996183145004434947d9915d77"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-jcl-6.2.0.jar",
          "url": "spring-jcl-6.2.0.jar",
          "size": 24534,
          "sha512": "a973976d29f6af462fbb34295a3bcb2b28f68a2051681f14cf58a8f02ec45955dc6622c3567baf676790c072e34b7b859ee843576b6ec2f4c32b08eb986aed89",
          "sha256": "2b59288f030ce77a89ec88aa426f32eb9a309056f3646dd5157f9f31f0204fd7",
          "sha1": "2b8e7bb1e751bf585e7db6de1d375c599e0c8cf5",
          "md5": "32d57c996183145004434947d9915d77"
        }
      ]
    }
  ]
}
